### ISSUE TITLE
nodisp appears not to be compatible with lists. 

### ISSUE THREAD

**Issue by stevenzins** [turnermm/nodisp#1]
turnermm: nodisp appears not to be compatible with lists. 

At the beginning of the file, nodisp works right, not showing text, till first item in the list. The first item is not shown. Remaining items each have bullet on one line and associated text on following line. Once it goes bad, the remaining text shows, erroneously. I can't find anything about this on this forum or google.
...Steve

**Comment by turnermm** [comment]
This should be fixed.

**Comment by stevenzins** [comment]
I did a few test.
You have fixed case where nodisp contains lists.
You have also fixed a case where nodisp contains a wrap.
Thank you very much.
...Steve
