### ISSUE TITLE
Alternative to acl syntax

### ISSUE THREAD

**Issue by mrhelbig** [turnermm/nodisp#5]
Hi - I found your plugin, after having first played around with the [ifauthex](https://www.dokuwiki.org/plugin:ifauthex) plugin. I really like the syntax used in that plugin to show content to either specific users or groups. In my usage case, it is groups that I am looking to show content to. However, I need the content to not be sent to the browser and so on recommendation I looked to your plugin, where the acl option looks as though it could work. 

Having played around with your plugin a little, I'm not sure how I can make your acl option work, as on my wiki there are a small number of editors, while all other users only have read permission. Users are added to groups and that is how we control access to pages (more commonly name spaces). Right now, when I need to show content on a particular page to a subset of the users, I use the include plugin and set an acl on the included file so that only the intended group can see that content. The problem with that strategy, is that the acl list is getting quite long, and only the Wiki admin can change acls.

So, if your plugin could support an third syntax, such as the following, it would be very useful, as it would allow any editor to mark up a portion of a page to only be visible to the intended group of users:
```
<nodisp @group_name>
your text here - only delivered to the browser of users in the acl group group_name
etc
</nodisp>
```

I know this is not a bug - bus wasn't sure where to put a feature request. I apologize if this is the wrong place for this kind of request.

Kind regards

**Comment by turnermm** [comment]
You are in the right place.
I am trying to wind down, but I will take a look at this. On the other hand, I am not sure why you can't use <nodisp 2 >
Or nodisp 4

**Comment by mrhelbig** [comment]
I'll leave the matter with you to consider. Just note that virtually all my users are logged in and have read at the root of the wiki. On each namespace (and sometimes sub-namespace) I have acls in place to give the **none** privilege to @ALL, and then allocate the **read** privilege to the relevant subgroup. I regularly have content on pages within these protected namespaces where I need to include content for only some users, who still only have the **read* privilege in that namespace. So in short, I can't distinguish between users based on their acl privilege - if I could, then your plugin would be exactly what I need.

**Comment by turnermm** [comment]
I've tried to follow this and looked at the code. But I will need concrete examples in order to determine a possible 
 solution.   DW's acl settings resolve to numbers and acl permissions are greater/ less than comparisons based on multiples of 2.  You seem to want names and I'm not sure how you plan to set these.

**Comment by mrhelbig** [comment]
Hi - sorry if I was not clear enough. I'm referring to data available in [devel:environment#info](https://www.dokuwiki.org/devel:environment#info). userinfo:grps is an array containing a list of all groups that the currently logged in user belongs to. My proposal is that we be able to limit content so that it is only visible if the logged in user is a member of the group listed in this syntax:
```
<nodisp @group_name>
your text here - only delivered to the browser of users having membership in the group group_name
etc
</nodisp>
```

They would also need to have at least read privileges on the page.

So for example: if we had a page [:coding:start](https://ww3.mrhelbig.com/coding:start). In the ACL manager, @ALL are given "None" as their access to the namespace, and a group called coders is given read privilege on the namespace. Also, another group called senior_coders is also given read privilege. The ACL manager would show the configuration [this way](https://gauss.mrhelbig.com/acls.png). Except, for testing purposes, I've allowed @ALL to this page, so you can see what I am trying to achieve.

Under normal ACL processing, anyone in the coders or senior_coders group have read privileges on this page.

I'd like to be able to have some information in the page that only the senior_coders can view when the page renders. Further more, I want that information to not be delivered to the end user's browser. You can see the effect of this by visiting [:coding:start](https://ww3.mrhelbig.com/coding:start) - where you will see the page with content hidden using the [ifauthex](https://www.dokuwiki.org/plugin:ifauthex) plugin, and also your plugin.

If you were a member of the @senior_coders group then the page [renders this way](https://gauss.mrhelbig.com/acls_senior_coder.png). The linked image shows the expected outcome. Ifauthex shows the additional content that the senior_coders should see, but there is no way to achieve the same results with the nodisp plugin.

I want to be able to do this with the nodisp plugin, so that the hidden content does not get sent to the end users browser.

To achieve this, I think your plugin would need to check the userinfo:grps data, rather than the perm data in the $INFO array. That said, I'm not a coder, so may be not on the right track here.

Thanks again for your time. If this is looking too difficult, then I understand, and I can continue to use my current strategy of using the include plugin and including sensitive information from another file that is restricted to my trusted group using the ACL system.

Kind regards

**Comment by turnermm** [comment]
You can now use your suggested syntax for groups, but without the @-sign, i.e. **group_name**, not **@group_nam**e:
```
<nodisp group_name>
your text here - only delivered to the browser of users having membership in the group group_name
</nodisp>
```
The url for this branch is:
https://github.com/turnermm/nodisp/archive/refs/heads/group.zip

This is a test distro.  It hasn't been released yet; you can install it using the manual tab of the extension manager.  I would hope that you will get back to me and let me know of anything that needs to be done.

**Comment by mrhelbig** [comment]
Thanks for doing this. I'll give it a proper test on the weekend.
Cheers

**Comment by mrhelbig** [comment]
Hi - sorry for taking a week to get back to this.

I've just installed the new code on my test server, and I can't seem to get it to recognise the new syntax.

You can see on my test page, [:coding:start](https://ww3.mrhelbig.com/coding:start), that the new usage case seems to behave in the same way as the first usage case mentioned in the documentation. That is, the text is hidden, but still viewable in the page source. Note, that test page has no ACL restrictions on reading the page.

When I log in as a member of the senior_coders group, ifauthex, now shows the hidden content, while your plugin still leaves the content hidden, but in the page source.

So, I think there are two things to resolve:
1. Group matching. My test user in in three groups, one of which is senior_coders.
2. Sensitive content should not be delivered to the end user's browser.

I can post some screen shots if that will help.

Thanks

**Comment by turnermm** [comment]
Afraid I jumped the gun on that. It wasn't actually finished but just a test version I was using in preview mode.

**Comment by turnermm** [comment]
I've spent some time this morning on this and it looks OK.  You'll have to test it.


https://github.com/turnermm/nodisp/archive/refs/heads/group.zip

**Comment by turnermm** [comment]
Have you tested this? If it works I  would like to merge it

**Comment by mrhelbig** [comment]
Hi Myron,

I’ll give it a go this afternoon.

Thanks

Alex

**Comment by mrhelbig** [comment]
HI Myron,

I've installed the updated plugin, but it doesn't seem to work for me. It seems that it shows contents that should be protected to any user with read permissions to the page, including non-logged in users.

Test page here: [coding:start](https://ww3.mrhelbig.com/coding:start)

I have this in my Dokuwiki source:
```
<nodisp senior_coders><WRAP indent2><WRAP errata>
This is sensitive information that will only be shown to members of senior_coders group. It has been protected using:<code>
<nodisp senior_coders>
sensitive stuff
</nodisp>
</code>
</WRAP></WRAP>
</nodisp>
```
The HTML outputted a logged-in user not in the senior_coders group is:
```
<div class = "nodisp_senior_coders"><!-- nodisp -->
<div class="wrap_indent2 plugin_wrap"><div class="wrap_errata plugin_wrap">
<p>
This is sensitive information that will only be shown to members of senior_coders group. It has been protected using:
</p>
<pre class="code">&lt;nodisp senior_coders&gt;
sensitive stuff
&lt;/nodisp&gt;</pre>
</div></div><!-- nodisp --></div>
```
Non logged-in users also see the same material. Note the test page I am using has read access for @ALL in the ACL manager.

Finally, I thought I should mention that I have not yet upgraded this server with the new hotfix to 2022-07-31a. I'm still running an un-patched Igor installation.

Thanks again for continuing to look at this.

Alex

**Comment by turnermm** [comment]
It's become a bit of  a challenge but I do think that I've worked it out now.  The URL is still the same:
  https://github.com/turnermm/nodisp/archive/refs/heads/group.zip

**Comment by mrhelbig** [comment]
Hi Myron - I can't see any change in behaviour.

BTW - Is there a version number I can check somewhere to make sure I am running your latest code? I assume that the file you are modifying is syntax/basic.php. The checksum for the file on my test server is:

MD5 (syntax/basic.php) = 2ce9149202c00ea296d5516417dd340d

Thanks

**Comment by turnermm** [comment]
That is the right version. But something weird is going on since I get the same result as you on my online server which runs Igor with PHP 7.2, but I get the desired result in my test server which runs PHP 8 with Igor, but I haven't been able to determine why there is this difference.

**Comment by turnermm** [comment]
Could you give me a list of your plugins?

**Comment by mrhelbig** [comment]
I'm using PHP 7.4 on my test server.
Plugins (there are a lot). Beyond the standard plugins I have these enabled:
- Advanced DokuWiki
- Anchor Plugin
- CAPTCHA Plugin
- Cell Background
- color syntax plugin
- Comment Syntax support
- folded plugin
- ifauthex plugin
- include plugin
- instantpage plugin
- MathJax plugin
- nodisp
- tabbox plugin
- Tab include plugin
- Table Width Plugin
- Tag Plugin
- TocTweak ver.2
- tplmod
- DokuWiki Upgrade Plugin
- Video Sharing Site Plugin
- Wrap Plugin

I have just disabled all of the plugins that are not bundled, except for your plugin and ifauthex - with no change in result.

**Comment by turnermm** [comment]
The latest effort is again at https://github.com/turnermm/nodisp/archive/refs/heads/group.zip
Below is the page markup, the result for which is here:
https://mturner.org/xen_server_igor/test/nodisp?do=


START BLOCK
\<nodisp special>
BLOCK: LEVEL STUFF
\</nodisp>
End Block

START NL \\\\
{nodisp num}
NEW LINE STUFF: __playground:test:nodisp Hidden to all but special group and root
{/nodisp} \\\\
End NL

START BLOCK
\<nodisp 8>
BLOCK: LEVEL 12345 STUFF
\</nodisp>
End Block

**Comment by mrhelbig** [comment]
Happy Days! It works!

Thankyou for your efforts with this. I will find this a very useful addition to your extension's capability.

Cheers
